# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Andrew Felder
email: andrew.felder@monroemi.gov
description: Homepage for Andrew Felder.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://andyfelder.com" # the base hostname & protocol for your site, e.g. http://example.com
logo: assets/img/Felder.jpg

# Additional pages to be displayed in navigation
# "title" is the title of the navigation item, "url" is the url, and "description" is the tooltip
navigation:
  - title: Home
    url: /
    description: Homepage
  - title: About
    url: /pages/about/
    description: About Andrew Felder
  - title: Item2
    url: /pages/item2/
    description: The second item

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - CNAME
  - README.md
  - vendor

